---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: check-sites
  namespace: monitoring-tools
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring-tools.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://devurandom.io
        - https://www.stackoverflow.co.uk
